image: $CI_REGISTRY/vlasami6/ctustyle3:master

pages:
  stage: deploy
  script:
    - mkdir -p public/
    - cp .fit-pages.yml public/
    - cd text
    - mmoptex vlasami6-dip.tex
    - mmoptex vlasami6-dip.tex
    - mmoptex vlasami6-dip.tex
    - cp vlasami6-dip.pdf ../public/
  artifacts:
    paths:
      - public/
    expire_in: 1 month
